run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Errors
    - errcheck
    - staticcheck
    - typecheck
    # Style
    - gofmt
    - goimports
    - goconst
    # Complexity
    - gocyclo
    # Security
    - gosec
    # Unused code
    - unused
    - ineffassign

linters-settings:
  goimports:
    local-prefixes: github.com/ethanolivertroy/cmvp-tui

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 2
    min-occurrences: 3

  gosec:
    excludes:
      - G104 # Audit errors not checked (handled by errcheck)

issues:
  exclude-rules:
    # Test files can have longer functions and unchecked errors
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
        - goconst

  max-issues-per-linter: 50
  max-same-issues: 10
